function print = print_values
global scenario_info_speed scenario_info_velocities scenario_info_start scenario_info_goal;
scenario_info_speed
scenario_info_velocities
scenario_info_start 
scenario_info_goal
end